name: PR Request

on:
    workflow_dispatch:
    pull_request:

jobs:
    pr-request:
         runs-on: ubuntu-latest
         steps: 
             - name: PR Details
               run : |
                echo "PR NO. : {{github.event.pull_request.number}}";
                echo "Target Branch :{{github.event.pull_request.base.ref}} "
                echo "Source Branch :{{github.event.pull_request.head.ref}} "
                echo "GateKeeper checks complete"
    
             

