name: Release Watcher

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  relase_watcher:
    runs-on: ubuntu-latest
    steps:
      - name: details of release
        run: |
          echo "Triggered by event: ${{ github.event_name }}"
          echo "Current date and time: $(date -u)"
          echo "Release watch complete"
