name: Subfolder Builder
on:
  push:
  workflow_dispatch:
jobs:
  build_subfolder:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: checkout runtime using marketplace action
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'

      - name: working directory
        run: pwd

      - name: list contents of working directory
        run: ls

      - name: finish build
        run: echo "Build folder confirmed"