name : Workflow Event

on :
    workflow_dispatch:
    push:
    pull_request:
    schedule: 
        - cron: '*/5 * * * *'
    

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo "This workflow was triggered by a(n) ${{github.event_name }} event."
